name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build & Test
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: |
          cd backend
          dotnet test
          dotnet publish Buildpoc.Web -c Release -o ../artifacts/backend/web
          dotnet publish Buildpoc.Someservice -c Release -o ../artifacts/backend/someservice

    - name: Upload Dockerfiles
      uses: actions/upload-artifact@v4
      with:
        name: dockerfiles
        path: ${{ github.workspace }}/_build/dockerfiles
        if-no-files-found: error

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ${{ github.workspace }}/artifacts
        if-no-files-found: error

  push-containers:
    runs-on: ubuntu-latest
    needs: build-test
    environment: container-registry

    permissions:
      contents: read
      packages: write

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - run: ls -R dockerfiles
    - run: ls -R artifacts

    - name: Web - Build container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfiles/Dockerfile.backend.web
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/buildpoc-web:${{ github.sha }}

    - name: Someservice - Build container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfiles/Dockerfile.backend.someservice
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/buildpoc-someservice:${{ github.sha }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: push-containers
    environment:
      name: staging
      url: ${{ steps.web-deploy.outputs.webapp-url }}
    permissions:
      contents: none

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Web - Deploy to Azure Web App
      id: web-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ghcr.io/${{ github.repository_owner }}/buildpoc-web:${{ github.sha }}
